cmake_minimum_required(VERSION 3.12)


file(GLOB_RECURSE GENERATED_DLL ${PROJECT_BINARY_DIR}/_deps/*.dll)

if (NOT CMAKE_SIZEOF_VOID_P STREQUAL "4")
    #64bit
    list(FILTER GENERATED_DLL EXCLUDE REGEX ".*x32.*")
    list(FILTER GENERATED_DLL EXCLUDE REGEX ".*x86.*")
else ()
    #32bit
    list(FILTER GENERATED_DLL EXCLUDE REGEX ".*x64.*")
endif ()

file(COPY ${GENERATED_DLL} DESTINATION ${CMAKE_BINARY_DIR})
